// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoYobuDb.Data;
using Oracle.EntityFrameworkCore.Metadata;

namespace MoYobuDb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MoYobuDb.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfileImage");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Anime", b =>
                {
                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int?>("anilistId")
                        .HasColumnName("ANILIST_ID");

                    b.Property<int?>("averageScore")
                        .HasColumnName("AVERAGE_SCORE");

                    b.Property<string>("coverImage")
                        .IsRequired()
                        .HasColumnName("COVER_IMAGE")
                        .HasColumnType("Varchar2(200)");

                    b.Property<string>("description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("Varchar2(2000)")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("endDate")
                        .HasColumnName("END_DATE")
                        .HasColumnType("Date");

                    b.Property<string>("englishTitle")
                        .HasColumnName("ENGLISH_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("episodeDuration")
                        .HasColumnName("EPISODE_DURATION")
                        .HasColumnType("Number(3)");

                    b.Property<int?>("episodes")
                        .HasColumnName("EPISODES")
                        .HasColumnType("Number(4)");

                    b.Property<int?>("episodesThreadId")
                        .HasColumnName("EPISODES_THREAD_ID");

                    b.Property<string>("format")
                        .HasColumnName("FORMAT")
                        .HasColumnType("Varchar2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("hashtag")
                        .HasColumnName("HASHTAG")
                        .HasColumnType("Varchar2(100)")
                        .HasMaxLength(100);

                    b.Property<string>("japaneseTitle")
                        .HasColumnName("JAPANESE_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("malId")
                        .HasColumnName("MAL_ID");

                    b.Property<int?>("reviewsThreadId")
                        .HasColumnName("REVIEWS_THREAD_ID");

                    b.Property<string>("romajiTitle")
                        .IsRequired()
                        .HasColumnName("ROMAJI_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<string>("season")
                        .HasColumnName("SEASON")
                        .HasColumnType("Varchar2(20)")
                        .HasMaxLength(20);

                    b.Property<string>("source")
                        .HasColumnName("SOURCE")
                        .HasColumnType("Varchar2(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("startDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("Date");

                    b.Property<string>("status")
                        .HasColumnName("STATUS")
                        .HasColumnType("Varchar2(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("studioId")
                        .HasColumnName("STUDIO_ID");

                    b.Property<int?>("userId");

                    b.HasKey("animeId");

                    b.HasIndex("episodesThreadId");

                    b.HasIndex("reviewsThreadId");

                    b.HasIndex("studioId");

                    b.HasIndex("userId");

                    b.ToTable("ANIMES");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeGenre", b =>
                {
                    b.Property<int>("animeGenreId")
                        .HasColumnName("ANIME_GENRE_ID");

                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int>("genreId")
                        .HasColumnName("GENRE_ID");

                    b.HasKey("animeGenreId");

                    b.HasIndex("animeId");

                    b.HasIndex("genreId");

                    b.ToTable("ANIME_GENRES");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeCharacter", b =>
                {
                    b.Property<int>("animeCharactersId")
                        .HasColumnName("ANIME_CHARACTERS_ID");

                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int>("characterId")
                        .HasColumnName("CHARACTER_ID");

                    b.HasKey("animeCharactersId");

                    b.HasIndex("animeId");

                    b.HasIndex("characterId");

                    b.ToTable("ANIME_CHARACTERS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeList", b =>
                {
                    b.Property<int>("animeListId")
                        .HasColumnName("ANIME_LIST_ID");

                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int>("listId")
                        .HasColumnName("LIST_ID");

                    b.Property<string>("userId");

                    b.HasKey("animeListId");

                    b.HasIndex("animeId");

                    b.HasIndex("listId");

                    b.ToTable("ANIME_LISTS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeStaff", b =>
                {
                    b.Property<int>("animeStaffId")
                        .HasColumnName("ANIME_STAFF_ID");

                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int>("staffId")
                        .HasColumnName("STAFF_ID");

                    b.HasKey("animeStaffId");

                    b.HasIndex("animeId");

                    b.HasIndex("staffId");

                    b.ToTable("ANIME_STAFFS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeTag", b =>
                {
                    b.Property<int>("animeTagId")
                        .HasColumnName("ANIME_TAG_ID");

                    b.Property<int>("animeId")
                        .HasColumnName("ANIME_ID");

                    b.Property<int>("tagId")
                        .HasColumnName("TAG_ID");

                    b.HasKey("animeTagId");

                    b.HasIndex("animeId");

                    b.HasIndex("tagId");

                    b.ToTable("ANIME_TAGS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Episode", b =>
                {
                    b.Property<int>("episodeId")
                        .HasColumnName("EPISODE_ID");

                    b.Property<int>("episodeThreadId")
                        .HasColumnName("EPISODES_THREAD_ID");

                    b.Property<string>("title")
                        .HasColumnName("TITLE")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50);

                    b.HasKey("episodeId");

                    b.HasIndex("episodeThreadId");

                    b.ToTable("EPISODES");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.EpisodesThread", b =>
                {
                    b.Property<int>("episodesThreadId")
                        .HasColumnName("EPISODES_THREAD_ID");

                    b.HasKey("episodesThreadId");

                    b.ToTable("EPISODES_THREADS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Genre", b =>
                {
                    b.Property<int>("genreId")
                        .HasColumnName("GENRE_ID");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnName("TITLE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.HasKey("genreId");

                    b.ToTable("GENRES");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Character", b =>
                {
                    b.Property<int>("characterId")
                        .HasColumnName("CHARACTER_ID");

                    b.Property<int?>("animeId");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnName("BIRTHDATE")
                        .HasColumnType("Date");

                    b.Property<string>("description")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("Varchar2(4000)")
                        .HasMaxLength(7000);

                    b.Property<string>("largeImgUrl")
                        .HasColumnName("LARGE_IMG_URL")
                        .HasColumnType("Varchar2(200)");

                    b.Property<int?>("mangaId");

                    b.Property<string>("mediumImgUrl")
                        .HasColumnName("MEDIUM_IMG_URL")
                        .HasColumnType("Varchar2(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("nameNative")
                        .HasColumnName("NAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surname")
                        .HasColumnName("SURNAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surnameNative")
                        .HasColumnName("SURNAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("voiceActorId")
                        .HasColumnName("VOICE_ACTOR_ID");

                    b.HasKey("characterId");

                    b.HasIndex("animeId");

                    b.HasIndex("mangaId");

                    b.HasIndex("voiceActorId");

                    b.ToTable("CHARACTERS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Manga", b =>
                {
                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.Property<int?>("anilistId")
                        .HasColumnName("ANILIST_ID");

                    b.Property<int?>("chapters")
                        .HasColumnName("CHAPTERS")
                        .HasColumnType("Number(4)");

                    b.Property<string>("descriptions");

                    b.Property<DateTime?>("endDate")
                        .HasColumnName("END_DATE")
                        .HasColumnType("Date");

                    b.Property<string>("englishTitle")
                        .HasColumnName("ENGLISH_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<string>("format")
                        .HasColumnName("FORMAT")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("img");

                    b.Property<string>("japaneseTitle")
                        .HasColumnName("JAPANESE_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("malId")
                        .HasColumnName("MAL_ID");

                    b.Property<int?>("reviewsThreadId")
                        .HasColumnName("REVIEWS_THREAD_ID");

                    b.Property<string>("romajiTitle")
                        .IsRequired()
                        .HasColumnName("ROMAJI_TITLE")
                        .HasColumnType("Varchar2(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("score")
                        .HasColumnName("SCORE")
                        .HasColumnType("Number(3)");

                    b.Property<string>("source")
                        .HasColumnName("SOURCE")
                        .HasColumnType("Varchar2(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("startDate")
                        .HasColumnName("START_DATE")
                        .HasColumnType("Date");

                    b.Property<string>("status")
                        .HasColumnName("STATUS")
                        .HasColumnType("Varchar2(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("userId");

                    b.HasKey("mangaId");

                    b.HasIndex("reviewsThreadId");

                    b.HasIndex("userId");

                    b.ToTable("MANGAS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaGenre", b =>
                {
                    b.Property<int>("mangaGenreId")
                        .HasColumnName("MANGA_GENRE_ID");

                    b.Property<int?>("characterId");

                    b.Property<int>("genreId")
                        .HasColumnName("GENRE_ID");

                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.HasKey("mangaGenreId");

                    b.HasIndex("characterId");

                    b.HasIndex("genreId");

                    b.HasIndex("mangaId");

                    b.ToTable("MANGA_GENRES");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaCharacter", b =>
                {
                    b.Property<int>("mangaCharacterId")
                        .HasColumnName("MANGA_CHARACTER_ID");

                    b.Property<int>("characterId")
                        .HasColumnName("CHARACTER_ID");

                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.HasKey("mangaCharacterId");

                    b.HasIndex("characterId");

                    b.HasIndex("mangaId");

                    b.ToTable("MANGA_CHARACTERS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaList", b =>
                {
                    b.Property<int>("mangaListId")
                        .HasColumnName("MANGA_LIST_ID");

                    b.Property<int>("listId")
                        .HasColumnName("LIST_ID");

                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.Property<string>("userId");

                    b.HasKey("mangaListId");

                    b.HasIndex("listId");

                    b.HasIndex("mangaId");

                    b.ToTable("MANGA_LISTS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaStaff", b =>
                {
                    b.Property<int>("mangaStaffId")
                        .HasColumnName("MANGA_STAFF_ID");

                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.Property<int>("staffId")
                        .HasColumnName("STAFF_ID");

                    b.HasKey("mangaStaffId");

                    b.HasIndex("mangaId");

                    b.HasIndex("staffId");

                    b.ToTable("MANGA_STAFFS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaTag", b =>
                {
                    b.Property<int>("mangaTagId")
                        .HasColumnName("MANGA_TAG_ID");

                    b.Property<int>("mangaId")
                        .HasColumnName("MANGA_ID");

                    b.Property<int>("tagId")
                        .HasColumnName("TAG_ID");

                    b.HasKey("mangaTagId");

                    b.HasIndex("mangaId");

                    b.HasIndex("tagId");

                    b.ToTable("MANGA_TAGS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MyList", b =>
                {
                    b.Property<int>("listId")
                        .HasColumnName("LIST_ID");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("Varchar2(30)")
                        .HasMaxLength(30);

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnName("type");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnName("USER_ID");

                    b.Property<int?>("userId1");

                    b.HasKey("listId");

                    b.HasIndex("userId1");

                    b.ToTable("LISTS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .HasColumnName("REVIEW_ID");

                    b.Property<int?>("animeId");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnName("CONTENT")
                        .HasColumnType("Varchar2(4000)")
                        .HasMaxLength(4000);

                    b.Property<int?>("mangaId");

                    b.Property<DateTime>("myDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("MY_DATE")
                        .HasColumnType("Date");

                    b.Property<int>("reviewsThreadId")
                        .HasColumnName("REVIEWS_THREAD_ID");

                    b.Property<int>("score")
                        .HasColumnName("SCORE")
                        .HasColumnType("Number(3)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnName("TITLE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("userId")
                        .HasColumnName("USER_ID");

                    b.Property<int?>("userId1");

                    b.HasKey("reviewId");

                    b.HasIndex("animeId");

                    b.HasIndex("mangaId");

                    b.HasIndex("reviewsThreadId");

                    b.HasIndex("userId1");

                    b.ToTable("REVIEWS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.ReviewsThread", b =>
                {
                    b.Property<int>("reviewsThreadId")
                        .HasColumnName("REVIEWS_THREAD_ID");

                    b.HasKey("reviewsThreadId");

                    b.ToTable("REVIEWS_THREADS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Staff", b =>
                {
                    b.Property<int>("staffId")
                        .HasColumnName("STAFF_ID");

                    b.Property<int?>("animeId");

                    b.Property<string>("birthPlace")
                        .HasColumnName("BIRTH_PLACE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("birthday")
                        .HasColumnName("BIRTHDAY")
                        .HasColumnType("Date");

                    b.Property<int?>("mangaId");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("nameNative")
                        .IsRequired()
                        .HasColumnName("NAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surname")
                        .HasColumnName("SURNAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surnameNative")
                        .HasColumnName("SURNAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.HasKey("staffId");

                    b.HasIndex("animeId");

                    b.HasIndex("mangaId");

                    b.ToTable("STAFFS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Studio", b =>
                {
                    b.Property<int>("studioId")
                        .HasColumnName("STUDIO_ID");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("VARCHAR2(50)")
                        .HasMaxLength(50);

                    b.HasKey("studioId");

                    b.ToTable("STUDIOS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Tag", b =>
                {
                    b.Property<int>("tagId")
                        .HasColumnName("TAG_ID");

                    b.Property<string>("title")
                        .HasColumnName("TITLE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.HasKey("tagId");

                    b.ToTable("TAGS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.User", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnName("USER_ID");

                    b.Property<bool>("askForReviewer");

                    b.Property<string>("desciption")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnType("Varchar2(4000)")
                        .HasMaxLength(4000);

                    b.Property<bool>("isReviewer");

                    b.Property<string>("profileImg")
                        .HasColumnName("PROFILE_IMG")
                        .HasColumnType("Varchar2(200)");

                    b.Property<string>("userAspId")
                        .HasColumnName("USER_ASP_ID")
                        .HasColumnType("Nvarchar2(450)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnName("USERNAME")
                        .HasColumnType("Varchar2(20)")
                        .HasMaxLength(20);

                    b.HasKey("userId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.VoiceActor", b =>
                {
                    b.Property<int>("voiceActorId")
                        .HasColumnName("VOICE_ACTOR_ID");

                    b.Property<string>("birthPlace")
                        .HasColumnName("BIRTH_PLACE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("birthdate")
                        .HasColumnName("BIRTHDATE")
                        .HasColumnType("Date");

                    b.Property<string>("img");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("nameNative")
                        .IsRequired()
                        .HasColumnName("NAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnName("SURNAME")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.Property<string>("surnameNative")
                        .IsRequired()
                        .HasColumnName("SURNAME_NATIVE")
                        .HasColumnType("Varchar2(50)")
                        .HasMaxLength(50);

                    b.HasKey("voiceActorId");

                    b.ToTable("VOICE_ACTORS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MoYobuDb.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MoYobuDb.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MoYobuDb.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Anime", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.EpisodesThread", "episodesThread")
                        .WithMany()
                        .HasForeignKey("episodesThreadId");

                    b.HasOne("MoYobuDb.Models.Tables.ReviewsThread", "reviewsThread")
                        .WithMany()
                        .HasForeignKey("reviewsThreadId");

                    b.HasOne("MoYobuDb.Models.Tables.Studio", "studio")
                        .WithMany("animes")
                        .HasForeignKey("studioId");

                    b.HasOne("MoYobuDb.Models.Tables.User")
                        .WithMany("favouritesAnime")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeGenre", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime", "anime")
                        .WithMany("animeGenres")
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Genre", "genre")
                        .WithMany("animeGenres")
                        .HasForeignKey("genreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeCharacter", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime", "anime")
                        .WithMany()
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Character", "character")
                        .WithMany("animeCharacters")
                        .HasForeignKey("characterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeList", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime", "anime")
                        .WithMany("animeLists")
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.MyList", "myList")
                        .WithMany("animeLists")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeStaff", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime", "anime")
                        .WithMany("animeStaffs")
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Staff", "staff")
                        .WithMany("animeStaffs")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.AnimeTag", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime", "anime")
                        .WithMany("animeTags")
                        .HasForeignKey("animeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Tag", "tag")
                        .WithMany("animeTags")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Episode", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.EpisodesThread", "episodeThread")
                        .WithMany("episodes")
                        .HasForeignKey("episodeThreadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Character", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime")
                        .WithMany("characters")
                        .HasForeignKey("animeId");

                    b.HasOne("MoYobuDb.Models.Tables.Manga")
                        .WithMany("characters")
                        .HasForeignKey("mangaId");

                    b.HasOne("MoYobuDb.Models.Tables.VoiceActor", "voiceActor")
                        .WithMany("characters")
                        .HasForeignKey("voiceActorId");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Manga", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.ReviewsThread", "reviewsThread")
                        .WithMany()
                        .HasForeignKey("reviewsThreadId");

                    b.HasOne("MoYobuDb.Models.Tables.User")
                        .WithMany("favouritesManga")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaGenre", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Character")
                        .WithMany("mangaGenres")
                        .HasForeignKey("characterId");

                    b.HasOne("MoYobuDb.Models.Tables.Genre", "genre")
                        .WithMany("mangaGenres")
                        .HasForeignKey("genreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Manga", "manga")
                        .WithMany("mangaGenres")
                        .HasForeignKey("mangaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaCharacter", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Character", "character")
                        .WithMany()
                        .HasForeignKey("characterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Manga", "manga")
                        .WithMany("mangaCharacters")
                        .HasForeignKey("mangaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaList", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.MyList", "myList")
                        .WithMany("mangaLists")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Manga", "manga")
                        .WithMany("mangaLists")
                        .HasForeignKey("mangaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaStaff", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Manga", "manga")
                        .WithMany("mangaStaffs")
                        .HasForeignKey("mangaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Staff", "staff")
                        .WithMany("mangaStaffs")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MangaTag", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Manga", "manga")
                        .WithMany("mangaTags")
                        .HasForeignKey("mangaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.Tag", "tag")
                        .WithMany("mangaTags")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.MyList", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.User", "user")
                        .WithMany("myLists")
                        .HasForeignKey("userId1");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Review", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime")
                        .WithMany("reviews")
                        .HasForeignKey("animeId");

                    b.HasOne("MoYobuDb.Models.Tables.Manga")
                        .WithMany("reviews")
                        .HasForeignKey("mangaId");

                    b.HasOne("MoYobuDb.Models.Tables.ReviewsThread", "reviewsThread")
                        .WithMany("reviews")
                        .HasForeignKey("reviewsThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoYobuDb.Models.Tables.User", "user")
                        .WithMany("reviews")
                        .HasForeignKey("userId1");
                });

            modelBuilder.Entity("MoYobuDb.Models.Tables.Staff", b =>
                {
                    b.HasOne("MoYobuDb.Models.Tables.Anime")
                        .WithMany("staffs")
                        .HasForeignKey("animeId");

                    b.HasOne("MoYobuDb.Models.Tables.Manga")
                        .WithMany("staffs")
                        .HasForeignKey("mangaId");
                });
#pragma warning restore 612, 618
        }
    }
}
